---
- name: CentOS package update
  yum:
    name: '*'
    state: latest

- name: Install Dependency Packages
  yum:
    name:
      - wget
      - curl
      - redhat-lsb-core
    state: present
  become: true

- name: Download percona-release package
  get_url:
    url: "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
    dest: "/tmp/percona-release-latest.noarch.rpm"

- name: Install percona-release package
  yum:
    name: "/tmp/percona-release-latest.noarch.rpm"
    state: present
  become: true

- name: CentOS package update
  yum:
    name: '*'
    state: latest

- name: Install pmm2-client
  yum:
    name: pmm2-client
    state: present
  become: true
