# syntax=docker/dockerfile:1

FROM rockylinux/rockylinux:8.4
ENV container docker

RUN dnf install glibc-langpack-en -y
RUN dnf -qy module disable postgresql -y
RUN dnf update -y
RUN dnf install sudo -y
RUN dnf install python3 -y
RUN dnf install ca-certificates -y
RUN dnf install openssh-clients -y
RUN dnf install openssh-server -y
RUN dnf install which -y