# syntax=docker/dockerfile:1

FROM centos:8

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
RUN yum makecache --refresh
RUN yum install iproute -y
RUN yum install sudo -y
RUN yum install python3 -y
RUN yum install ca-certificates -y
RUN yum install openssh-clients -y
RUN yum install openssl -y
RUN yum install openssh-server -y
RUN yum install which -y
