include ../../Makefile.mk

build-debian10:
	docker compose up pmmserver1-debian10 -d

build-ubuntu20:
	docker compose up pmmserver1-ubuntu20 -d

build-centos7:
	docker compose up pmmserver1-centos7 -d
