---
# TODO : Install extension and create extension in pg
- name: Create Extension - {{ pg_extension }}
  community.postgresql.postgresql_query:
    query: >-
      CREATE EXTENSION {{ pg_extension }}
    port: "{{ pg_port }}"
    db: "{{ pg_database }}"
    login_user: "{{ pg_owner }}"
    login_unix_socket: "{{ pg_unix_socket_directories[0] }}"
    autocommit: true
  no_log: "{{ disable_logging }}"
  become: true
  become_user: "{{ pg_owner }}"
