---
- name: Check required variables for this role
  include_role:
    name: common
    tasks_from: check_required_variables
  vars:
    required_variables:
      - pg_type
      - pg_version

# Entry point of the extension_manage role
- name: Include the setup_extension.yml
  include_tasks: setup_extension.yml
  when: "'setup_extension' in lookup('tmax_opensql.postgres.supported_roles', wantlist=True)"
