---
- name: Check Operating System,  PostgreSQL type, PostgreSQL version
  include_role:
    name: common
    tasks_from: check_version.yml

- name: Set Extensions version
  include_tasks: set_extension_version.yml
  when:
    - ansible_os_family == 'RedHat'
    - pg_major_version|int >= 14

- name: Reference Postgres variables
  include_vars: "{{ pg_type }}_{{ ansible_os_family }}.yml"

- name: Get facts on current container
  community.docker.current_container_facts:

- name: Set whether to use the system user or not
  set_fact:
    use_system_user: false
  when: ansible_module_running_in_container

- name: Include extension_package_manage tasks
  include_tasks: extension_package_manage.yml
  loop: "{{ pg_extension_list }}"
  loop_control:
    loop_var: pg_extension
  when:
    - pg_extension_list is defined
    - pg_extension_list|length > 0
