---
pg_major_version: "{{ pg_version | int }}"
pg_port: 5432
pg_database: "postgres"
pg_owner: "postgres"
pg_service: "{{ lookup('tmax_opensql.postgres.pg_service') }}"
pg_unix_socket_directories:
  - "/var/run/postgresql"

tuned_configuration_dir: "/etc/tuned"
supported_tuned_configuration_dir:
  - "/etc/tuned"
  - "/usr/lib/tuned"

# related tuned
tuned_profile: "postgres"
enable_tuned: false
