---
- name: Set the os variable
  set_fact:
    os: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"

- name: Check support for Operating System
  fail:
    msg: "Operating System = {{ os }} not supported."
  when: os not in supported_os

- name: Include the pgbouncer_set_databases
  include_tasks: pgbouncer_set_databases.yml

- name: Include the pgbouncer_set_userlist
  include_tasks: pgbouncer_set_userlist.yml
