---
- name: Check pgbouncer_auth_user_list validation
  fail:
    msg: "pgbouncer_auth_user_list.username or password is not defined."
  with_items: "{{ pgbouncer_auth_user_list }}"
  loop_control:
    loop_var: user_item
  when:
    - pgbouncer_auth_user_list|length > 0
    - user_item.state is not defined or user_item.state == 'present'
    - (user_item.username is not defined or user_item.username|length < 1) or (user_item.password is not defined or user_item.password|length < 1)

- name: Manage PgBouncer auth. file entries in {{ pgbouncer_auth_file }}
  lineinfile:
    path: "{{ pgbouncer_auth_file }}"
    line: '"{{ user_item.username }}" "{{ user_item.password }}"'
    regexp: "^\\\"{{ user_item.username | regex_escape() }}\\\".*"
    state: "{{ user_item.state | default('present') }}"
    create: true
    mode: 0600
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
  when: pgbouncer_auth_user_list|length > 0
  with_items: "{{ pgbouncer_auth_user_list }}"
  loop_control:
    loop_var: user_item
  become: true

- name: Reload PgBouncer configuration
  shell:
    cmd: kill -HUP $(cat {{ pgbouncer_pid_file }})
  changed_when: false
  become: true
