---
- name: Disable builtin postgresql module
  shell: >
    dnf -qy module disable postgresql
  args:
    executable: /bin/bash
  register: disable_builtin_postgres
  changed_when: disable_builtin_postgres.rc == 0
  failed_when: disable_builtin_postgres.rc != 0
  ignore_errors: true
  become: true
  when: ansible_distribution_major_version in ['8','9']

- name: Install require python package on EL7
  package:
    name:
      - python-pycurl
      - libselinux-python
      - python-ipaddress
    state: present
  when: ansible_distribution_major_version == '7'
  become: true

- name: Install require python package on EL8, EL9
  package:
    name:
      - python3-pycurl
      - python3-libselinux
    state: present
  become: true
  when: ansible_distribution_major_version in ['8','9']

- name: Install require python package up to PG v14
  package:
    name:
      - python3
      - python3-libs
    state: present
  become: true
  when: pg_major_version|int >= 14

- name: Install Required Package
  package:
    name:
      - libxslt
      - libicu
      - ca-certificates
      - glibc-common
    state: present
  become: true

- name: Install Postgres
  package:
    name:
      - postgresql{{ pg_major_version }}-libs-{{ pg_version }}
      - postgresql{{ pg_major_version }}-{{ pg_version }}
      - postgresql{{ pg_major_version }}-server-{{ pg_version }}
      - postgresql{{ pg_major_version }}-contrib-{{ pg_version }}
    state: present
  become: true
  when: not rpm_install

- name: Install Postgres rpm list
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  become: true
  loop: "{{ rpm_list }}"
  when:
    - rpm_install
    - rpm_list|length > 0

- name: Install psycopg2 on EL7
  package:
    name:
      - python2-psycopg2
    state: present
  when: ansible_distribution_major_version == '7'
  become: true

- name: Install psycopg2 on EL8
  package:
    name:
      - python3-psycopg2
    state: present
  when: ansible_distribution_major_version in ['8','9']
  become: true

- name: Install json-c 0.13.1-3.el8 on rhel8
  package:
    name:
      - python3-psycopg2
    state: present
  when: ansible_distribution_major_version == '9'
  become: true
    
