---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Set fact pg_service for RedHat
  set_fact:
    pg_service: "postgresql-{{ pg_major_version }}.service"
  when: ansible_os_family == 'RedHat'

- name: Stop pg service if running
  ansible.builtin.systemd:
    name: "{{ pg_service }}"
    state: stopped
    enabled: false
  when:
    - ansible_facts.services[pg_service] is defined
    - ansible_facts.services[pg_service].state == 'running'
    - use_system_user
  become: true

- name: Include ensure_postgresql_process.yml tasks
  include_tasks: ensure_postgresql_process.yml
  vars:
    - _postgresql_exists: ""
  when: not use_system_user

- name: Stop pg process
  ansible.builtin.command: >
    {{ pg_bin_path }}/pg_ctl -D {{ pg_default_data }} stop
  when:
    - not use_system_user
    - _postgresql_exists.rc == 0
  become: true
  become_user: "{{ pg_owner }}"

- name: Remove require python package on EL7
  package:
    name:
      - python2-psycopg2
    state: absent
  when: ansible_distribution_major_version == '7'
  become: true

- name: Remove require python package on EL8 , EL9
  package:
    name:
      - python3-psycopg2
    state: absent
  become: true
  when: ansible_distribution_major_version in ['8','9']

- name: Remove Postgres
  package:
    name:
      - postgresql{{ pg_major_version }}-libs
      - postgresql{{ pg_major_version }}
      - postgresql{{ pg_major_version }}-server
      - postgresql{{ pg_major_version }}-contrib
    state: absent
  become: true
