---
- name: Set the os variable
  set_fact:
    os: "{{ ansible_distribution | replace('RedHat', 'RHEL') }}{{ ansible_distribution_major_version }}"

- name: Check support for Operating System
  fail:
    msg: "Operating System = {{ os }} not supported."
  when: os not in supported_os

- name: Include OS and pg_type dependent variables
  include_vars: "{{ pg_type }}_{{ ansible_os_family }}.yml"

- name: Get facts on current container
  community.docker.current_container_facts:

- name: Set whether to use the system user or not
  set_fact:
    use_system_user: false
  when: ansible_module_running_in_container

- name: Check Pgbouncer variable validation
  include_tasks: check_pgbouncer_variable.yml

- name: Include the pgbouncer_install
  include_tasks: pgbouncer_install.yml

- name: Include the pgbouncer_setup
  include_tasks: pgbouncer_setup.yml
