---
- name: Ensure postgres log directory exists
  ansible.builtin.file:
    path: "{{ pg_log }}"
    owner: "{{ pg_owner }}"
    group: "{{ pg_group }}"
    mode: 0700
    state: directory
  become: true
  when: pg_log|length > 0

- name: Ensure postgres log directory's file privilege
  ansible.builtin.file:
    path: "{{ pg_log }}"
    owner: "{{ pg_owner }}"
    group: "{{ pg_group }}"
    state: directory
    recurse: true
  become: true
  when: pg_log|length > 0

- name: Ensure postgres local wal archive directory exists
  ansible.builtin.file:
    path: "{{ pg_local_wal_archive_dir }}"
    owner: "{{ pg_owner }}"
    group: "{{ pg_group }}"
    mode: 0700
    state: directory
  become: true
  when: pg_local_wal_archive_dir|length > 0

- name: Ensure postgres local wal archive directory's file privilege
  ansible.builtin.file:
    path: "{{ pg_local_wal_archive_dir }}"
    owner: "{{ pg_owner }}"
    group: "{{ pg_group }}"
    state: directory
    recurse: true
  become: true
  when: pg_local_wal_archive_dir|length > 0
