---
- name: Check pg_locale exists
  ansible.builtin.shell: |
    set -o pipefail
    locale -a | grep -i {{ pg_locale }}
  when: pg_locale | length > 0
  failed_when: false
  register: locale_stat

- name: Set pg_locale to default locale
  ansible.builtin.set_fact:
    pg_locale: "{{ 'en_US.utf8' if ansible_os_family == 'RedHat' else 'C.UTF-8' if ansible_os_family == 'Debian' }}"
  when: locale_stat.stdout_lines | length < 1
