---
pg_major_version: "{{ pg_version | int }}"

pgpool2_version: 4.3
pgpool2_patch_version: 6
# We don't have the choice of the version with community PostgreSQL
pgpool2_package_name: "pgpool-II"
pcp_package_name: "pgpool-II-pcp"
pgpool2_configuration_file: "/etc/pgpool-II/pgpool.conf"
pgpool2_user: "postgres"
pgpool2_group: "postgres"

# Systemd unit file
pgpool2_systemd_unit_file: "/usr/lib/systemd/system/pgpool-II.service"
pgpool2_systemd_conf_file: "/etc/sysconfig/pgpool-II"

# pcp file
pcp_configuration_file: "/etc/pgpool-II/pcp.conf"
pcppass_file: "{{ pg_user_home }}/.pcppass"

pgpool2_pid_file_name: "/var/run/pgpool-II/pgpool.pid"
pgpool2_logdir: "/var/log/pgpool-II"
# Directory containing SSL keys and certs
pgpool2_ssl_dir: "/etc/pgpool-II/ssl"
pgpool2_bin_path: "/usr/bin"

pgpool2_node_id_file: "/etc/pgpool-II/pgpool_node_id"

# failover script file in pgpool
pgpool2_failover_file: "/etc/pgpool-II/failover.sh"
pgpool2_follow_primary_file: "/etc/pgpool-II/follow_primary.sh"

pgpool2_listen_addresses: '*'
pgpool2_pcp_port: 9898
pgpool2_wd_port: 9000
pgpool2_wd_heartbeat_port: 9694

# Default user to login from pgpool
pg_pgpool_database: "postgres"
pg_pgpool_user: "pgpool"
pg_pgpool_user_password: ""
input_password: ""

# pcp admin user
pcp_admin_user: "pcpadmin"
pcp_admin_user_password: ""

# Postgres user that pgpool2 will use to check Postgres nodes roles in load
# balance mode
pgpool2_sr_check_user: "pgpool2"
# If empty or not defined, a random password will be generated
pgpool2_sr_check_password: ""

# health check mdoe
pgpool2_health_check_user: "pgpool2"
# If empty or not defined, a random password will be generated
pgpool2_health_check_password: ""

pgpool2_user_map: []

# pgpool command
pgpool_start_command: "{{ pgpool2_bin_path }}/pgpool -f {{ pgpool2_configuration_file }}"
pgpool_stop_command: "{{ pgpool2_bin_path }}/pgpool -f {{ pgpool2_configuration_file }} -m fast stop"
pgpool_reload_command: "{{ pgpool2_bin_path }}/pgpool -f {{ pgpool2_configuration_file }} reload"

# pgpool socket directories
pgpool_socket_directories:
  - "/tmp"

pgpool2_ssl_csr_dn:
  CN: "pgpool-server.fqdn"
  O: ""
  OU: ""
  L: ""
  ST: ""
  C: ""
  EMAIL: "example@mail.com"

pg_port: 5432
pg_database: "postgres"
pg_instance_name: "main"
pg_user_home: "/var/lib/pgsql"
pg_default_data: "/var/lib/pgsql/{{ pg_major_version }}/data"
pgpass_file: "{{ pg_user_home }}/.pgpass"

# pg replication user
pg_replication_user: "repuser"

ssh_port: 22

supported_os:
  - CentOS7
  - CentOS8
  - RHEL7
  - RHEL8
  - Rocky8

supported_pg_version:
  - 14.0
  - 14.1
  - 14.2
  - 14.3
  - 14.4
  - 14.5
  - 14.6
  - 14.7
  - 14.8
  - 15.0
  - 15.1
  - 15.2
  - 15.3
  - 15.4

supported_pgpool2_version:
  - 4.3
