---
- name: Remove docker force
  package:
    name: "{{ docker_package }}"
    state: absent
  become: true
  when: force_docker

- name: Install required package in pmmserver
  package:
    name:
      - yum-utils
      - python3-docker
      - python3-pip
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install python docker module
  command: >-
    pip3 install docker

# Install docker Repository
- name: Install Docker Repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: true
  when: ansible_os_family == 'RedHat'

# There may be a conflict between the previously installed docker version and the docker-ce version.
# Error: docker-ce conflicts with 2:docker version
# Error: docker-ce-cli conflicts with 2:docker version
- name: Install Docker
  package:
    name: docker-ce
    state: present
  become: true

# Start docker service
- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes
  when: use_system_user
  become: true

# Pull pmm-server docker image
- name: Pull pmm-server docker image
  ansible.builtin.command: >-
    docker pull {{ pmm_server_image }}
  register: docker_pull_image
  changed_when: docker_pull_image.rc == 0

# Create Volume
- name: Create a volume
  docker_volume:
    name: "{{ inventory_hostname }}-data"
    state: present
