---
# Install docker
- name: Install Docker
  package:
    name: docker
    state: present
  become: true

# Start docker service
- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

# Pull pmm-server docker image
- name: Pull pmm-server docker image
  ansible.builtin.command: >
    docker pull percona/pmm-server:2

# Create Volume
- name: Create Volume
  ansible.builtin.command: >
    docker volume create pmm-data

# Run docker
- name: Run docker
  ansible.builtin.command: >
    docker run --detach --restart always \
    -- publish 443:443 \
    -v pmm-data:/srv \
    --name pmm-server \
    percona/pmm-server:2
