---
- name: Fetch pgpool server SSH public key
  slurp:
    src: "{{ pg_user_home + '/.ssh/id_rsa.pub' }}"
  register: _pgpool2_server_ssh_public_key_b64
  become: true

- name: Set _pgpool2_server_ssh_public_key
  set_fact:
    _pgpool2_server_ssh_public_key: "{{ _pgpool2_server_ssh_public_key_b64.content | b64decode | trim }}"

- name: Ensure {{ pgpool2_user }} SSH public key is on the Postgres server
  lineinfile:
    path: "{{ pg_user_home + '/.ssh/authorized_keys' }}"
    owner: "{{ pg_owner }}"
    group: "{{ pg_group }}"
    mode: 0600
    line: "{{ _pgpool2_server_ssh_public_key }}"
    create: true
  become: false
  delegate_to: "{{ server.inventory_hostname }}"
  loop: "{{ _pg_cluster_nodes }}"
  loop_control:
    loop_var: server

- name: Run ssh-keyscan and Add known hosts
  include_tasks: add_known_hosts.yml
  loop: "{{ _pg_cluster_nodes }}"
  loop_control:
    loop_var: server
