---
- name: Generate the pcp_admin_user_password
  include_role:
    name: common
    tasks_from: generate_password
  vars:
    input_user: "{{ pcp_admin_user }}"
    input_password: "{{ pcp_admin_user_password }}"
  no_log: "{{ disable_logging }}"
  run_once: true
  when: pcp_admin_user_password|length < 1

- name: Set pcp_admin_user_password
  set_fact:
    pcp_admin_user_password: "{{ input_password }}"
  when: pcp_admin_user_password|length < 1
  run_once: true

- name: Add pcp_admin_user
  include_role:
    name: manage_pgpool2
    tasks_from: pcp_manage_users
  vars:
    input_pcp_users:
      - name: "{{ pcp_admin_user }}"
        pass: "{{ pcp_admin_user_password }}"
  no_log: "{{ disable_logging }}"
  when: pcp_admin_user_password|length > 1

- name: Add .pcppass file
  lineinfile:
    path: "{{ pcppass_file }}"
    line: "localhost:{{ pgpool2_pcp_port }}:{{ pcp_admin_user }}:{{ pcp_admin_user_password }}"
    regexp: "^localhost:{{ pgpool2_pcp_port }}:{{ pcp_admin_user }}:*"
    create: true
    mode: 0600
  become: true
  become_user: "{{ pgpool2_user }}"
