---
- name: Disable builtin postgresql module on EL8
  shell: >
    dnf -qy module disable postgresql
  args:
    executable: /bin/bash
  register: disable_builtin_postgres
  changed_when: disable_builtin_postgres.rc == 0
  failed_when: disable_builtin_postgres.rc != 0
  ignore_errors: true
  become: true
  when:
    - ansible_distribution_major_version == '8'
    - ansible_os_family == 'RedHat'

- name: Include RedHat variable in install_dbserver
  include_vars: ../../install_dbserver/vars/{{ pg_type }}_{{ ansible_os_family }}.yml

- name: Install PostgreSQL lib package
  ansible.builtin.yum:
    name: "{{ rpm_install_path }}-{{ pg_version }}-1PGDG.rhel{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install pgpoolII package on RedHat
  ansible.builtin.set_fact:
    pgpool2_package_name: "https://www.pgpool.net/yum/rpms/{{ pgpool2_version }}/redhat/rhel-\
      {{ ansible_distribution_major_version }}-{{ ansible_architecture }}/\
      pgpool-II-pg{{ pg_major_version }}-{{ pgpool2_version }}.{{ pgpool2_patch_version }}-1pgdg.rhel{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm"
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Install pgpoolII requried package on RedHat
  ansible.builtin.yum:
    name:
      - "libevent"
      - "libmemcached"
      - "{{ pgpool2_package_name }}"
    state: present
    disable_gpg_check: true
  when:
    - ansible_os_family == 'RedHat'
  become: true

- name: Install openssl package on RedHat
  ansible.builtin.package:
    name: "openssl"
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - pgpool2_ssl
  become: true
