---
- name: Send failover script file
  template:
    src: "{{ failover_script_local_path }}"
    dest: "{{ pgpool2_failover_file }}"
    owner: "{{ pgpool2_user }}"
    group: "{{ pgpool2_group }}"
    mode: 0755
  become: true

- name: Send follow primary script file
  template:
    src: "{{ follow_primary_script_local_path }}"
    dest: "{{ pgpool2_follow_primary_file }}"
    owner: "{{ pgpool2_user }}"
    group: "{{ pgpool2_group }}"
    mode: 0755
  become: true
