---
# Task for setting up pgpoolII watchdog feature

- name: Create sudo rules for {{ pgpool2_user }}
  template:
    src: ./templates/pgpool.sudoers.d.conf.template
    dest: /etc/sudoers.d/pgpool
    mode: 0640
  when: use_system_user
  become: true

- name: Watchdog configuration
  set_fact:
    pgpool2_watchdog_configuration: >-
      [
        {
          'key': 'use_watchdog',
          'value': 'on',
        },
        {
          'key': 'delegate_IP',
          'value': '{{ pgpool2_vip }}',
          'quoted': true
        },
        {
          'key': 'if_up_cmd',
          'value': '{{ if_up_command }}',
          'quoted': true
        },
        {
          'key': 'if_down_cmd',
          'value': '{{ if_down_command }}',
          'quoted': true
        },
        {
          'key': 'arping_cmd',
          'value': '{{ arping_command }}',
          'quoted': true
        }
      ]

- name: Add pgpool2 nodes in watchdog configuration
  set_fact:
    pgpool2_watchdog_configuration: >-
      {{ pgpool2_watchdog_configuration }} + [
        {
          'key': 'hostname{{ ansible_loop.index0 }}',
          'value': '{{ node_item }}',
          'quoted': true
        },
        {
          'key': 'pgpool_port{{ ansible_loop.index0 }}',
          'value': '{{ pgpool2_port }}',
          'quoted': false
        },
        {
          'key': 'wd_port{{ ansible_loop.index0 }}',
          'value': '{{ pgpool2_wd_port }}',
          'quoted': false
        },
        {
          'key': 'heartbeat_hostname{{ ansible_loop.index0 }}',
          'value': '{{ node_item }}',
          'quoted': true
        },
        {
          'key': 'heartbeat_port{{ ansible_loop.index0 }}',
          'value': '{{ pgpool2_wd_heartbeat_port }}',
          'quoted': false
        }
      ]
  loop: "{{ pgpool2_node_list }}"
  loop_control:
    extended: true
    loop_var: node_item

# Update the configuration file
- name: Include pgpooL2_manage_configuration
  include_role:
    name: manage_pgpool2
    tasks_from: pgpool2_manage_configuration
  vars:
    pgpool2_configuration_lines: "{{ pgpool2_watchdog_configuration }}"
