- name: "Ensure /etc/systemd/system/{{ repmgrd_service }}.service.d exists"
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ repmgrd_service }}.service.d"
    mode: "0744"
    state: directory
  become: true
  when:
    - ansible_os_family == 'RedHat'
    - use_system_user

- name: "Write /etc/systemd/system/{{ repmgrd_service }}.service.d/override.conf"
  ansible.builtin.template:
    src: override.conf.j2
    dest: "/etc/systemd/system/{{ repmgrd_service }}.service.d/override.conf"
    mode: "0600"
    owner: root
    group: root
  become: true
  when:
    - ansible_os_family == 'RedHat'
    - use_system_user

- name: "Write /etc/default/repmgrd"
  ansible.builtin.template:
    src: default.repmgrd.j2
    dest: /etc/default/repmgrd
    mode: "0700"
    owner: root
    group: root
  become: true
  when: ansible_os_family == 'Debian'
