---
- name: Enable and start repmgrd
  ansible.builtin.systemd:
    name: "{{ repmgrd_service }}"
    state: restarted
    daemon_reload: true
  become: true
  when: use_system_user

- name: Start repmgrd start
  ansible.builtin.command: >
    {{ pg_bin_path }}/repmgrd -f {{ repmgr_configuration_file }} -p {{ repmgr_pid_file }} -d --verbose
  when: not use_system_user
  become: true
  become_user: "{{ pg_owner }}"
