---
barman_user: "barman"
barman_group: "barman"
barman_configuration_file: "/etc/barman.conf"
barman_configuration_files_directory: "/etc/barman.d"
barman_lock_directory: "/var/run/barman"
barman_log_file: "/var/log/barman/barman.log"
barman_log_level: "INFO"
barman_compression: "gzip"

etc_hosts_lists: []
use_hostname: false
update_etc_file: true
