---
- name: Gather service facts
  service_facts:

- name: Stop pg service if running
  systemd:
    name: "{{ pg_service }}"
    state: stopped
  when:
    - ansible_facts.services[pg_service] is defined
    - ansible_facts.services[pg_service].state == 'running'
    - use_system_user
  become: true

- name: Check if we have postgres pid exists or not
  ansible.builtin.stat:
    path: "{{ pg_default_data }}/postmaster.pid"
  become: true
  register: postgres_pid_file

- name: Stop pg process
  ansible.builtin.command: >
    {{ pg_bin_path }}/pg_ctl -D {{ pg_default_data }} stop
  when:
    - not use_system_user
    - postgres_pid_file.stat.exists
  become: true
  become_user: "{{ pg_owner }}"

- name: Drop the default debian database
  shell: >
    {{ pg_deb_drop_cluster }} {{ pg_major_version }} {{ pg_instance_name }}
  args:
    executable: /bin/bash
  changed_when: drop_cluster.rc == 0
  failed_when: drop_cluster.rc != 0
  when: ansible_os_family == 'Debian'
  become: true

- name: Remove postgres data directory if exists
  file:
    path: "{{ pg_data }}"
    state: absent
  become: true

- name: Remove postgres log directory if exists
  file:
    path: "{{ pg_log }}"
    state: absent
  become: true
  when: pg_log|length > 0

- name: Remove postgres wal directory if exists
  file:
    path: "{{ pg_wal }}"
    state: absent
  become: true
  when: pg_wal|length > 0

- name: Remove postgres local wal archive directory if exists
  file:
    path: "{{ pg_local_wal_archive_dir }}"
    state: absent
  become: true
  when: pg_local_wal_archive_dir|length > 0
