---
pgbouncer_systemd_unit_file: "/etc/systemd/system/pgbouncer.service.d/pgbouncer.conf"
pg_major_version: "{{ pg_version | int }}"

# Enable SSL
pgbouncer_ssl: true
pgbouncer_ssl_csr_dn:
  CN: "pgbouncer-server.fqdn"
  O: ""
  OU: ""
  L: ""
  ST: ""
  C: ""
  EMAIL: "example@mail.com"

available_pool_mode:
  - transaction
  - session
  - query

available_auth_type:
  - pam
  - hba
  - cert
  - md5
  - scram-sha-256
  - plain
  - trust
  - any

supported_os:
  - CentOS7
  - CentOS8
  - RHEL7
  - RHEL8
  - RHEL9
  - Rocky8
  - Rocky9

supported_pgbouncer_version:
  - "1.19.1-42"
  - "1.19.1-1"

external_package_retries: 15
package_retry_delay: 10