---
- name: Reference Postgres variables
  include_vars: "{{ pg_type }}_{{ ansible_os_family }}.yml"

- name: Find the hba file location
  community.postgresql.postgresql_query:
    login_user: "{{ pg_owner }}"
    port: "{{ pg_port }}"
    login_unix_socket: "{{ pg_unix_socket_directories[0] }}"
    query: "show hba_file;"
    db: "{{ pg_database }}"
  when: input_pg_hba_ip_addresses|length > 0
  become: true
  become_user: "{{ pg_owner }}"
  no_log: "{{ disable_logging }}"
  register: hba_info

- name: Manage ip address entries into pg_hba file
  community.postgresql.postgresql_pg_hba:
    dest: "{{ hba_info.query_result[0].hba_file }}"
    contype: "{{ line_item.contype | default('hostssl') }}"
    users: "{{ line_item.users | default('all') }}"
    source: "{{ line_item.source }}"
    databases: "{{ line_item.databases | default('all') }}"
    method: "{{ line_item.method | default('scram-sha-256') }}"
    state: "{{ line_item.state | default('present') }}"
    create: true
  become: true
  become_user: "{{ pg_owner }}"
  when: input_pg_hba_ip_addresses|length > 0
  with_items: "{{ input_pg_hba_ip_addresses }}"
  loop_control:
    loop_var: line_item
  no_log: "{{ disable_logging }}"
  register: hba_update
  throttle: 1

- name: Check if we have postgres pid exists or not
  ansible.builtin.stat:
    path: "{{ pg_default_data }}/postmaster.pid"
  become: true
  register: postgres_pid_file

- name: Fetch PostgreSQL pid
  shell: |
    set -o pipefail && cat {{ pg_default_data }}/postmaster.pid  | head -1
  register: postgres_pid
  changed_when: postgres_pid|length > 0
  when: postgres_pid_file.stat.exists

- name: Reload the pg process
  ansible.builtin.command: >
    kill -HUP {{ postgres_pid.stdout }}
  when:
    - hba_update.changed
    - postgres_pid_file.stat.exists
  become: true
  become_user: "{{ pg_owner }}"
