---
- name: Generate pcp users md5 password
  command:
    cmd: >-
      script -q -c '{{ pgpool2_bin_path }}/pg_md5 {{ pcp_user.pass }}'
  become: true
  become_user: "{{ pgpool2_user }}"
  when:
    - pcp_user|length > 0
    - pcp_user.state is not defined or pcp_user.state == 'present'
  register: pcp_password_out

- name: Update pcp.conf
  lineinfile:
    path: "{{ pcp_configuration_file }}"
    line: "{{ pcp_user.name }}:{{ pcp_password_out.stdout }}"
  become: true
  become_user: "{{ pgpool2_user }}"
  when:
    - pcp_user|length > 0
    - pcp_user.state is not defined or pcp_user.state == 'present'

- name: Update .pcppass
  lineinfile:
    path: "{{ pcppass_file }}"
    line: "localhost:{{ pgpool2_pcp_port }}:{{ pcp_user.name }}:{{ pcp_user.pass }}"
    regexp: "^localhost:{{ pgpool2_pcp_port }}:{{ pcp_user.name }}:*"
    create: true
    mode: 0600
  become: true
  become_user: "{{ pgpool2_user }}"
  when:
    - pcp_user|length > 0
    - pcp_user.state is not defined or pcp_user.state == 'present'
