---
pgpool2_configuration: []
pgpool2_users: []
pcp_users: []

# Database variables
pg_data: "{{ pg_user_home + '/' + pg_major_version + '/data' if ansible_os_family == 'RedHat' else \
      pg_user_home + '/' + pg_major_version  + '/' + pg_instance_name if ansible_os_family == 'Debian' }}"
pg_owner: "postgres"
